### ISSUE TITLE
Original file input being removed with clones

### ISSUE THREAD

**Issue by collin-garvey** [transloadit/jquery-sdk#10]
Not sure if this is intended behavior –

I have a simple form where users can upload a profile photo. It has one file input, but it is part of a multi-step set up process so I don't want the page refreshing. The photo selects and uploads fine, but I believe my original input field is being lumped in with the "clones" when they get removed from the DOM. 

Ideally I'd like to retain the original input with its event intact so that a user can select a different photo after uploading one. It seems that currently the input and associated events are destroyed upon submit. 

Plugin options: 
    wait: true 
    onResult: simple handler to insert image in to DOM

**Comment by hspindell** [comment]
Hi @collin-garvey @felixge, I know this thread is four years old but I was wondering if this problem has been solved? Is there a way to basically reset the uploader on the same form without re-rendering the HTML and reinitializing on it?

**Comment by tim-kos** [comment]
Hey @hspindell,

This should work out of the box now. If you cancel or complete an assembly, the file uploader goes back to square zero.

You can try this out in our demo section (which uses the jQuery SDK) and upload several groups of files one after the other.

If you have a custom progress bar in your app code, you need to reset that yourself, of course. But SDK-wise, everything should work fine with multiple runs.
