### ISSUE TITLE
destroy/detach method

### ISSUE THREAD

**Issue by ninjatux** [transloadit/jquery-sdk#12]
Hi guys,

I ran into a situation where I needed to attach/detach transloadit plugin dynamically.
Currently I resolved this issue simply unbinding it with

``` javascript
$("formSelector").unbind("submit.transloadit");
```

but a method exposed would be better and easier to use.

**Comment by tim-kos** [comment]
There will be a `destroy` method in the upcoming version 3.0.0 and it also unbinds the now name-spaced input `change` events. https://github.com/transloadit/jquery-sdk/blob/v3/js/lib/jquery.transloadit2.js#L597

:+1:

**Comment by tonyrivas** [comment]
Can you please confirm the correct format for this.
:) there is no documentation :(

**Comment by tim-kos** [comment]
```
var $el = $('#upload-form');
$el.transloadit({
  wait: true
});

var uploader = $el.data('transloadit.uploader');
// then call some methods on the uploader object
uploader.destroy();
```

:)
