### ISSUE TITLE
Submit form when no file is selected.

### ISSUE THREAD

**Issue by mromagnoli** [transloadit/jquery-sdk#14]
I was having some issues when user submits form and no file is selected. I believed that **processZeroFiles** option takes cares of this, but I think it doesn't.

Looking at init() function: 

``` javascript
Uploader.prototype.init = function($form, options) {
    this.$form = $form;
    this.options($.extend({}, OPTIONS, options || {}));

    var self = this;
    $form.bind('submit.transloadit', function() {
      self.validate();
      self.detectFileInputs();
      if (!self._options['processZeroFiles'] && self.$files.length === 0) {
        self.submitForm();
      } else {
        self.getBoredInstance();
      }

      return false;
    });

    this.includeCss();
  };
```

Checks if processZeroFiles is !false and no file is selected, so if it's true it submits the form anyway.

Then I look submitForm() function:

``` javascript
 Uploader.prototype.submitForm = function() {
    if (this.$fileClones) {
      this.$fileClones.remove();
    }

    if (this.assembly !== null) {
      $('<textarea/>')
        .attr('name', 'transloadit')
        .text(JSON.stringify(this.assembly))
        .prependTo(this.$form)
        .hide();
    }

    this.$form
      .unbind('submit.transloadit')
      .submit();
  };
```

And after all the checks, it unbinds **submit.transloadit** and submits to the form action setted, in my case, and written in docs, **api2.transloadit.com/assemblies** so I am redirected to that url seeing something like this:

![cap tloadit](https://f.cloud.github.com/assets/1746271/606557/88540d06-cd2c-11e2-8776-2d759985a035.png)

Hope this will be useful.

**Comment by tim-kos** [comment]
Closing this as `processZeroFiles` has been merged almost two years ago. I just forgot to close this issue. :/
