### ISSUE TITLE
Document title set to null when complete

### ISSUE THREAD

**Issue by davidgovea** [transloadit/jquery-sdk#17]
Noticed that my document's title was being set to `null` after uploading a file.

The `Uploader`'s `documentTitle` attribute is initialized to `null` [on line 72](https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit2.js#L74)

Then, documentTitle is set to `document.title`, but **[only for Firefox](https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit2.js#L448)**

Then, in various places, `document.title` is reassigned to the uploader.documentTitle.

Am I missing something here? I don't see this.documentTitle get assigned anywhere else.. just NULL, or the current value if you're in firefox.
This can't be the intended behavior..

I'm using this workaround for now:

``` js
$element.transloadit({...});
var uploader = $el.data('transloadit.uploader');
uploader.documentTitle = document.title;
```

**Comment by tim-kos** [comment]
This has been fixed in the meantime.
