### ISSUE TITLE
$el.transloadit('start'); not working

### ISSUE THREAD

**Issue by dolarsrg** [transloadit/jquery-sdk#20]
Hi,

reading the docs at: https://transloadit.com/docs#jquery-plugin
![screen shot 2014-03-19 at 19 26 37](https://f.cloud.github.com/assets/763298/2464219/3e9f82bc-af94-11e3-92b6-fd57d2889ac2.png)

it is said you can trigger the upload process manually by calling:
<code>$el.transloadit('start');</code>

But I can't see this option at the source code ( https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit2.js ) and is not working showing no errors at log console.

Should it work? Or documentation is deprecated?

**Comment by tim-kos** [comment]
It calls the start method here: https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit2.js#L342

Do you have some files actually selected or form data provided?

**Comment by tim-kos** [comment]
Closing this as invalid/old.
