### ISSUE TITLE
A failed assembly triggers a file upload to our servers

### ISSUE THREAD

**Issue by KieranP** [transloadit/jquery-sdk#21]
With the following configuration, if TransloadIt returns a AUTH_EXPIRED response or some other code, then the error dialog reflects that, but in the background, it still goes ahead and uploads the file (Chrome shows "Uploading (5%)" in the bottom left corner).

```
wait: true
processZeroFiles: false
```

If TransloadIt sends back an error code, it should abort the upload completely to prevent bandwidth on our and your end.

What I think needs to happen:
- The XMLHTTPRequest object needs to be stored as $request (or other variable( on the upload object for reference later
- In the event of either `Uploader.prototype.stop` or `Uploader.prototype.cancel` being called, then you need to call $request.abort() to stop the upload

Also, in this event, the transloadit form field shouldn't be filled in, and the form shouldn't be autosubmitted. At the moment, if people cancel, then hit the submit button again, it submits the form with an empty file field and a filled in transloadit form field.

**Comment by tim-kos** [comment]
Unfortunately, this is hard to do with our current iframe method of uploading. Our new version 3.0.0 uses XHR for uploading and stops the upload behind the scenes when there is an error.

The related code is here:

https://github.com/transloadit/jquery-sdk/blob/v3/js/lib/jquery.transloadit2.js#L907
https://github.com/transloadit/jquery-sdk/blob/v3/js/lib/jquery.transloadit2.js#L913
