### ISSUE TITLE
Uploader.start() should gracefully handle when files are null

### ISSUE THREAD

**Issue by ajsharp** [transloadit/jquery-sdk#29]
Currently, line 318 expects `this.$files` to be a jquery object, and results in an undefined function error if it's not. This code should fail gracefully if `this.$files` is null.

This is the code:

``` javascript
    this.$files.each(function() {
      var $clone = $(this).clone(true);
      self.$fileClones = self.$fileClones.add($clone);
      $clone.insertAfter(this);
    });
```

**Comment by tim-kos** [comment]
In our upcoming version `3.0.0`, we explicitely call find on the form to detect file inputs. This will always return a jQuery object, even if we do not have file input fields in the form. Code is here: https://github.com/transloadit/jquery-sdk/blob/v3/js/lib/jquery.transloadit2.js#L837

The same is true in the `master` branch. https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit2.js#L486

I am not sure how you got the undefined function call. Please let me know if this is still an issue and I will happily investigate this again. :)
