### ISSUE TITLE
clone input when using formData

### ISSUE THREAD

**Issue by richfisher** [transloadit/jquery-sdk#43]
I clone the repo https://github.com/tim-kos/transloadit-drag-and-drop, and it works fine. While I update jquery.transloadit to the latest version, the issue that clone the input after dropping an image occurs.

Reproduce steps:
1. clone https://github.com/tim-kos/transloadit-drag-and-drop
2. edit index.html
3. replace `<script src="lib/transloadit.js"></script>` with `<script src="https://assets.transloadit.com/js/jquery.transloadit2-v2-latest.js"></script>`
4. open index.html in browser.
5. drag and drop an image.
6. there will be 2 inputs. if you drop again, there will be 4 inputs, if you drop again, there will be 8 inputs........

![8inputs](https://cloud.githubusercontent.com/assets/830633/10933980/a5f08e18-8317-11e5-8f06-3e21674453aa.png)

**Comment by kvz** [comment]
@tim-kos
