### ISSUE TITLE
BORED_INSTANCE_ERROR

### ISSUE THREAD

**Issue by sescobb27** [transloadit/jquery-sdk#48]
Hi For more than once, i'm getting upload errors. Seems that there's a cache problem with some json transload webservice using your JQuery SDK

```
XMLHttpRequest cannot load https://s3.amazonaws.com/infra-us-east-1.transloadit.com/cached_instances.json. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'https://ec-ember-staging.herokuapp.com' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
```

``` js
{ 
  error: "BORED_INSTANCE_ERROR", 
  message: "Could not find a bored instance. Could not query S3 for cached uploaders from url: https://s3.amazonaws.com/infra-us-east-1.transloadit.com/cached_instances.json"
}
```

This happens when uploader tries a GET from http://infra-us-east-1.transloadit.com.s3.amazonaws.com/cached_instances.json and aborts.

I think is because i'm using an `ajaxPrefilter` but not sure: 

``` js
Ember.$.ajaxPrefilter(function (options) {
  options.crossDomain = {
    crossDomain: true
  };
  options.xhrFields = {
    withCredentials: true
  };
});
```

if that's not the problem why is this happening? and/or how can i solved it? it used to work until now

BTW: it works sometimes and sometimes it isn't

thanks

**Comment by tim-kos** [comment]
This has been fixed. And in the upcoming `v3` version of the SDK, the bored instance logic has been removed entirely.
