### ISSUE TITLE
v3: Drag&Drop onFileSelect callback behaves in an undocumented way.

### ISSUE THREAD

**Issue by DecayConstant** [transloadit/jquery-sdk#52]
HI! 
The documentation says the the first argument of the `onFileSelect` callback will be the filename, but when it's called after dropping a file into a Drag&Drop area, the first argument is an Object of file metadata, including the name.

I don't know which way is the intended way going forward, but I figured they should be consistent.

**Comment by tim-kos** [comment]
Ah yes, thank you. The documentation is off there. It should indeed be a file object. :) I will fix the Readme, thank you.

**Comment by DecayConstant** [comment]
Another thing I've run into is that `onFileSelect` behaves differently if you use drag&drop vs. doing it the regular way (clicking on a file input).

Drag&Drop passes in the FileObject, but clicking on the input and using the OS's file picker returns a filename string.

https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit.js#L752
vs.
https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit.js#L146

I can deal with this by type-checking, but I don't know if this is intended or even fixable.

**Comment by tim-kos** [comment]
Thank you. This will be fixed with the next release, which should happen either today or next week. 👍
