### ISSUE TITLE
V3: this._modal.renderCancelling() is still invoked when modal is set to false.

### ISSUE THREAD

**Issue by rveitch** [transloadit/jquery-sdk#55]
We've encountered a breaking issue in v3 of the SDK that occurs when cancelling an upload if the `modal` parameter is set to `false` for custom progress rendering.  An error will be thrown by [`this._modal.renderCancelling()`](https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit.js#L571) as it is not wrapped in a conditional to prevent it from being invoked when modal is false, and the modal object will then be undefined.

I've submitted PR #53 to resolve the issue, but until it is merged we'll need to continue using a forked custom build of the SDK with this hotfix included.

Thanks in advance!

**Comment by tim-kos** [comment]
I merged this just now. I am working on another (minor) patch for something else and will make a new release tonight.

Thank you for the reminder. I was on vacation last week and only saw the PR now. 👍
