### ISSUE TITLE
v3: Assumes global $, does not play well with Browserify and ES6 modules

### ISSUE THREAD

**Issue by djanowski** [transloadit/jquery-sdk#56]
Would you take a patch so that all classes receive a reference to the jQuery object?

**Comment by tim-kos** [comment]
Hm I am building the project using browserify, but admittedly there are only es5 modules.

If you submitted a PR, I'd accept it. 👍

**Comment by tim-kos** [comment]
Hey @djanowski 

Do you still plan to create a PR for this?

**Comment by krolow** [comment]
Hey! What if we do something like this:

```js
!((factory) => {
  if (typeof module === 'object' && typeof module.exports === 'object')  {
    try {
      const jquery = require('jquery')
      factory(jquery)
    } catch (_) {
      factory(window.jQuery)
    }
  } else {
    factory(window.jQuery)
  }
})(($) =>
```

To initialize the plugin, so if we have the `require` we would use that to load jquery, in case we can't we fallback for `window.jQuery`

So it would work well in es6 modules + browserfy and I think it would keep the same behavior as today if we have window jquery.

Let me know what do you guys think and if that sounds good for you I will open a PR

**Comment by goto-bus-stop** [comment]
yeah, wrapping the entire bundle in that should work. we'd also need to [derequire](https://www.npmjs.com/package/derequire) the bundle in order for it to be browserified again by users, else browserify will try to resolve the `require()` calls inside the generated bundle.

**Comment by djanowski** [comment]
PR https://github.com/transloadit/jquery-sdk/pull/63

**Comment by kvz** [comment]
❤️

**Comment by djanowski** [comment]
I'll keep this issue open until new version is deployed to the CDN. Thanks!

**Comment by djanowski** [comment]
👋 Can you please let us know when this is deployed? Thanks!

**Comment by kvz** [comment]
Wanted to but ran into: `You do not have permission to publish "transloadit-jquery-sdk"`. @tim-kos can you do this?

Happy holidays!

--
Kevin van Zonneveld (kvz.io)
Co-founder at Transloadit (transloadit.com)
Core-author of tus (tus.io)

**Comment by djanowski** [comment]
Ping?

**Comment by tim-kos** [comment]
Just pushed this. It will be live in around 30min.

Sorry for the delay here. Thanks for implementing this!
