### ISSUE TITLE
Removed function Assembly.stopStatusFetching is still being called.

### ISSUE THREAD

**Issue by DecayConstant** [transloadit/jquery-sdk#61]
`Assembly.stopStatusFetching()` was removed in this commit: https://github.com/transloadit/jquery-sdk/commit/a273b23c3c7e0b34f2271f73ddae57c73c989fa1

But it is still being called here in `Uploader.stop()`: https://github.com/transloadit/jquery-sdk/blob/master/js/lib/jquery.transloadit.js#L531

Which causes calls to Uploader.destroy() to crash.

**Comment by tim-kos** [comment]
Thank you for reporting this!
