### ISSUE TITLE
Add timeouts for internet connection tests

### ISSUE THREAD

**Issue by arturi** [transloadit/jquery-sdk#66]
I left a tab open with jquery-sdk in it, and it produced a lit of network events in console:

<img width="1192" alt="screen shot 2018-03-27 at 4 43 54 pm" src="https://user-images.githubusercontent.com/1199054/37995305-fad25c1a-31e1-11e8-8a75-b6e5cd792271.png">

Not a big deal, but it does use some cpu/battery/network cycles, and we can probably do better.

Maybe you can simply rely on the browser events https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events, like we do [in Uppy](https://github.com/transloadit/uppy/blob/1eb235ace031b1902a176412d2b50351ed3fe37e/src/core/Core.js#L746-L763)?

**Comment by tim-kos** [comment]
Yep! Will work on that. Cheers.
