### ISSUE TITLE
maxNumberOfUploadedFiles - Error still returned on subsequent upload attempts even within allowable limits.

### ISSUE THREAD

**Issue by richt222** [transloadit/jquery-sdk#74]
Hello!

I'm using `maxNumberOfUploadedFiles` to restrict the number of uploads. 

If I attempt to upload more than the specified max number of uploads, I get the `MAX_FILES_EXCEEDED` error returned as you would expect. So far, so good.

However, if I *then* attempt to upload a number of files within the max allowable - even just a single file - I still get the `MAX_FILES_EXCEEDED` error returned.

It's as though Transloadit still has in memory the files from the previous attempt.

This is the code I'm using...

```javascript
$('#vehicle-images-form').transloadit({
    wait: true,
    autoSubmit: false,
    triggerUploadOnFileSelection: true,
    processZeroFiles: false,
    maxNumberOfUploadedFiles: 2,
    params: {
      auth: { key: "xxx" },
      template_id: "xxx"
    },                    
    onError: function(assembly) {
        console.log(assembly);
        // handle error
    },            
    onSuccess: function(assembly) {
        console.log(assembly);
        // do something
    }
});
```

**Comment by tim-kos** [comment]
Hey there,

I have checked the code and it is properly resetting `this._fileCount` when start() is called. Which version of SDK are you running?

**Comment by richt222** [comment]
Hi Tim,

Thanks for your response. I'm using v3 latest. Here is the complete code, boiled down for testing.

```html
<form id="pdfs-form" method="post" action="x.php">
	<input type="file" name="pdf_uploads" multiple="true" />	
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="https://assets.transloadit.com/js/jquery.transloadit2-v3-latest.js"></script>

<script type="text/javascript">

    $('#pdfs-form').transloadit({
        wait: true,
        autoSubmit: false,
        triggerUploadOnFileSelection: true,
        processZeroFiles: false,
        maxNumberOfUploadedFiles: 2,
        params: {
          auth: { key: "-redacted-" },
          template_id: "-redacted-"
        },                     
        onError: function(assembly) {
            console.log(assembly);
            alert(assembly.message);
        },            
        onSuccess: function(assembly) {
            console.log(assembly);
        }
    });

</script>
```

So, if I first select 3 files to upload, I get the max files exceeded error as expected. I then only select 1 file, but I still get the error response. Tested in the latest versions of both Chrome and Firefox on a mac, with the same result.

**Comment by tim-kos** [comment]
Hey there,

I pushed a fix. It will be deployed today.

**Comment by richt222** [comment]
Brilliant. Thanks, Tim!

**Comment by richt222** [comment]
Sorry Tim, I've just discovered that this does not work when using the Transloadit drop area to perform the uploads, rather than the traditional HTML file element.

Code as above, but adding the following to the form...

```
<div class="transloadit-drop-area" data-name="files"></div>
```

I'm hoping as it's related, it'll be an easy fix. Thanks!

**Comment by tim-kos** [comment]
Added to my todo for Friday.

**Comment by richt222** [comment]
Hi @tim-kos , sorry to bother you - just wondering if you managed to make any progress with this?

**Comment by tim-kos** [comment]
Sorry, not yet as I was sick. :/

But I will work on this today.

**Comment by tim-kos** [comment]
Hey Richard,

So I think the problem is that you are assuming another drag/drop will _replace_ the previously dragged files with the ones you just dragged again.

That's not true, though. Subsequent drag/drops will _add_ files (even the same ones) to the list of files-to-upload. This is to make it easier for the user to drag/drop files from multiple folders/locations. Does this make sense?

If you add

```
<div class="transloadit-file-preview-area"></div>
```

right below the drop-area this will become more apparent and you can then also choose to "Remove" certain files again.

**Comment by richt222** [comment]
Hi Tim,

No worries - sorry to hear you were ill, and hope you're feeling a lot better now!

Ok, thanks. It's not totally desirable to have the preview area, at least in our case for a few reasons.

1) It looks like all files are queued successfully for upload without problem, even though we already know at this stage there are too many of them to succeed.

2) We automatically trigger the upload to transloadit as soon as the files are added, rather than on  submission of the main form. So having the preview list prior to the upload sort of breaks the flow.

3) We already have our own preview area, which shows thumbnails once successfully uploaded (on callback form Transloadit).

Is there perhaps a function we can call manually to clear the files in the drag and drop area, upon receiving the max upload error? Even if we have to loop over the files one by one, removing each as we go?

**Comment by richt222** [comment]
Hi @tim-kos Any thoughts on the above? I still have a client waiting, so eager to solve this.

**Comment by tim-kos** [comment]
Still on my todo. I'll try to get to it on the weekend. If not, then on
Monday.

**Comment by richt222** [comment]
Hi @tim-kos Any progress with this? (sorry to ping you again on it!)

**Comment by tim-kos** [comment]
Sorry about the delay again.

The SDK has a `reset()` function, which is what you need. So something like this (untested):

```
const $el = $('#pdfs-form')
$el.transloadit({
        wait: true,
        autoSubmit: false,
        triggerUploadOnFileSelection: true,
        processZeroFiles: false,
        maxNumberOfUploadedFiles: 2,
        params: {
          auth: { key: "-redacted-" },
          template_id: "-redacted-"
        },                     
        onError: function(assembly) {
            console.log(assembly);
            alert(assembly.message);
            $el.data('transloadit.uploader').reset()
        },            
        onSuccess: function(assembly) {
            console.log(assembly);
        }
    });
```

Notice the `$el.data('transloadit.uploader').reset()`.

**Comment by richt222** [comment]
Excellent. Works :) Thanks so much @tim-kos !

**Comment by tim-kos** [comment]
Okay, great!
