### ISSUE TITLE
Progress event may return 0 as number of bytes expected in IE8

### ISSUE THREAD

**Issue by tidoust** [transloadit/jquery-sdk#8]
I've been running into troubles using the lib on IE8. As far as I can tell, the JSONP "success" callback may be called with an assembly object that has bytes_expected set to 0. When renderProgress is called, a division by zero occurs at line 515 and the progress variable becomes NaN. In turn, this makes jQuery crash on the call to animate at line 523.

Wrapping the division in an if loop that sets progress to 0 when bytes_expected is 0 solved the problem for me.

**Comment by tim-kos** [comment]
This has been fixed.
